### ISSUE TITLE
Crash on chat startup 

### ISSUE THREAD

**Issue by coolcodehere** [xiphirx/lizard#8]
Chat messages flash for a second and then app crashes. 

SDK version: 28
Running on Google Pixel 2 XL

[Error Dump](https://pastebin.com/vDJkhnPd)

**Comment by xiphirx** [comment]
Yeah this is due to a change in Android 28, just need to swap the operation

**Comment by coolcodehere** [comment]
Made a [PR](https://github.com/xiphirx/lizard/pull/9) for a fix.
